language: node_js
node_js:
    - "4"
cache:
  directories:
  - ~/.npm
  - node_modules
  
before_install:
  - sudo apt-get install wkhtmltopdf
    
install:
  - npm install
    
before_script:
  - git config --global user.name 'lzhr'
  - git config --global user.email 'lzhrsmile@gmail.com'

script:
  - rm -f node_modules/markdown-resume/assets/css/*
  - cp *.css node_modules/markdown-resume/assets/css/
#  - node node_modules/markdown-resume/bin/md2resume resume.md
# node node_modules/markdown-resume/bin/md2resume --pdf resume.md
#  - mv resume.html index.html
#  - node node_modules/markdown-resume/bin/md2resume 'resume-en.md'
#  - mv resume-en.html en/index.html
# For icon
  - cp source/_resume/template.html node_modules/markdown-resume/assets/templates/default.html
  - node node_modules/markdown-resume/bin/md2resume source/_resume/resume.md
  - node node_modules/markdown-resume/bin/md2resume source/_resume/resume-en.md
# Ugly
  #node node_modules/markdown-resume/bin/md2resume --pdf resume.md
  - mv source/_resume/resume.html index.html
  - mkdir  en
  - mv source/_resume/resume-en.html en/index.html
  
after_success:
    - git init
    - git symbolic-ref HEAD refs/heads/gh-pages
    - git remote add origin $DEPLOY_REPO
    - git add -A .
    - git commit -m 'Site updated by Travis CI'
    - git push --force --quiet origin gh-pages
